### ISSUE TITLE
The result of function toRGB multiplying by 2.55 should be rounded.

### ISSUE THREAD

**Issue by RubyHue** [csstools/postcss-lab-function#10]
const rgbValues = toRGB(...).map(channelValue => Math.max(Math.min(Math.round(channelValue * 2.55), 255), 0));

**Comment by romainmenke** [comment]
@RubyHue This has been resolved in the latest release.
This repo has moved to [@csstools/postcss-plugins](https://github.com/csstools/postcss-plugins)

If you have any further issues, you can find us there!
