### ISSUE TITLE
When the preserve option is true, CSS variable fallback value is overrided.

### ISSUE THREAD

**Issue by RubyHue** [csstools/postcss-lab-function#11]
In the README 'Options preserve' example:
```
--firebrick: rgb(178, 34, 34);
--firebrick: lab(40% 56.6 39);
color: var(--firebrick);
```
However in unsupported browser, color will fallback to initial value, because the last variable override the first one, so the rgb value is never used.
Should become:
```
--firebrick: rgb(178, 34, 34);
@supports (color: lab(40% 56.6 39)) {
  --firebrick: lab(40% 56.6 39);
}
```

**Comment by romainmenke** [comment]
@RubyHue This has also been resolved in the latest release.
This repo has moved to [@csstools/postcss-plugins](https://github.com/csstools/postcss-plugins)

If you have any further issues, you can find us there!
